export interface Wilaya {
  code: string;
  name: string;
  shippingCost: number;
}

export const wilayas: Wilaya[] = [
  { code: "01", name: "Adrar", shippingCost: 1200 },
  { code: "02", name: "Chlef", shippingCost: 600 },
  { code: "03", name: "Laghouat", shippingCost: 900 },
  { code: "04", name: "Oum El Bouaghi", shippingCost: 700 },
  { code: "05", name: "Batna", shippingCost: 700 },
  { code: "06", name: "Béjaïa", shippingCost: 600 },
  { code: "07", name: "Biskra", shippingCost: 800 },
  { code: "08", name: "Béchar", shippingCost: 1200 },
  { code: "09", name: "Blida", shippingCost: 400 },
  { code: "10", name: "Bouira", shippingCost: 500 },
  { code: "11", name: "Tamanrasset", shippingCost: 1500 },
  { code: "12", name: "Tébessa", shippingCost: 800 },
  { code: "13", name: "Tlemcen", shippingCost: 700 },
  { code: "14", name: "Tiaret", shippingCost: 700 },
  { code: "15", name: "Tizi Ouzou", shippingCost: 500 },
  { code: "16", name: "Alger", shippingCost: 300 },
  { code: "17", name: "Djelfa", shippingCost: 800 },
  { code: "18", name: "Jijel", shippingCost: 600 },
  { code: "19", name: "Sétif", shippingCost: 600 },
  { code: "20", name: "Saïda", shippingCost: 800 },
  { code: "21", name: "Skikda", shippingCost: 600 },
  { code: "22", name: "Sidi Bel Abbès", shippingCost: 700 },
  { code: "23", name: "Annaba", shippingCost: 600 },
  { code: "24", name: "Guelma", shippingCost: 700 },
  { code: "25", name: "Constantine", shippingCost: 500 },
  { code: "26", name: "Médéa", shippingCost: 500 },
  { code: "27", name: "Mostaganem", shippingCost: 600 },
  { code: "28", name: "M'Sila", shippingCost: 700 },
  { code: "29", name: "Mascara", shippingCost: 700 },
  { code: "30", name: "Ouargla", shippingCost: 1000 },
  { code: "31", name: "Oran", shippingCost: 500 },
  { code: "32", name: "El Bayadh", shippingCost: 1000 },
  { code: "33", name: "Illizi", shippingCost: 1500 },
  { code: "34", name: "Bordj Bou Arréridj", shippingCost: 600 },
  { code: "35", name: "Boumerdès", shippingCost: 400 },
  { code: "36", name: "El Tarf", shippingCost: 700 },
  { code: "37", name: "Tindouf", shippingCost: 1500 },
  { code: "38", name: "Tissemsilt", shippingCost: 700 },
  { code: "39", name: "El Oued", shippingCost: 900 },
  { code: "40", name: "Khenchela", shippingCost: 800 },
  { code: "41", name: "Souk Ahras", shippingCost: 700 },
  { code: "42", name: "Tipaza", shippingCost: 400 },
  { code: "43", name: "Mila", shippingCost: 600 },
  { code: "44", name: "Aïn Defla", shippingCost: 600 },
  { code: "45", name: "Naâma", shippingCost: 1000 },
  { code: "46", name: "Aïn Témouchent", shippingCost: 700 },
  { code: "47", name: "Ghardaïa", shippingCost: 1000 },
  { code: "48", name: "Relizane", shippingCost: 600 },
  { code: "49", name: "El M'Ghair", shippingCost: 1000 },
  { code: "50", name: "El Meniaa", shippingCost: 1100 },
  { code: "51", name: "Ouled Djellal", shippingCost: 900 },
  { code: "52", name: "Bordj Badji Mokhtar", shippingCost: 1500 },
  { code: "53", name: "Béni Abbès", shippingCost: 1300 },
  { code: "54", name: "Timimoun", shippingCost: 1400 },
  { code: "55", name: "Touggourt", shippingCost: 900 },
  { code: "56", name: "Djanet", shippingCost: 1500 },
  { code: "57", name: "In Salah", shippingCost: 1400 },
  { code: "58", name: "In Guezzam", shippingCost: 1500 },
];

export const formatDZD = (amount: number): string => {
  return `${amount.toLocaleString("fr-DZ")} DA`;
};
